### ISSUE TITLE
Ready for grading week 2 git lab assignment

### ISSUE THREAD

**Issue by vanufrovich-matc** [madisoncollege-it-programs/python-scripting-vanufrovich-matc#1]

**Comment by cethenmc** [comment]
Looks good, Viktoryia!

**Comment by cethenmc** [comment]
Hi, Viktoryia.  The first script that you added 12 days ago looks good, except it is not executable at the command line level.  Correct that for full credit.  Otherwise, this piece of week 2 will remain 6/8.
