### ISSUE TITLE
Week 3 - Never submitted.

### ISSUE THREAD

**Issue by cethenmc** [madisoncollege-it-programs/python-scripting-vanufrovich-matc#10]
Please let me know if you will keep a 0 out of 8 on this assignment, or if you plan to submit it this week.

**Comment by vanufrovich-matc** [comment]
I am planning to complete this assignment. 
Thank you!

**Comment by cethenmc** [comment]
Thank you, Viktoryia!  Do you think you will be able to finish any outstanding items for weeks 3 through 7 by Sunday?  I would like you to do them well if that is too much of a rush.  At the same time, I do want to close off the first half of the course soon if I can.

**Comment by vanufrovich-matc** [comment]
Understood. I will try to complete them all by Sunday.
Thank you for your patience.

**Comment by vanufrovich-matc** [comment]
Week3 lab String Formatting is ready for grading. Thanks!

**Comment by vanufrovich-matc** [comment]
Hi Chris,
Thank you for letting me know, I will keep 7 of 8 grade. Thank you!

**Comment by cethenmc** [comment]
Thank you, Viktoryia.
