### ISSUE TITLE
Week 4 - Never submitted.

### ISSUE THREAD

**Issue by cethenmc** [madisoncollege-it-programs/python-scripting-vanufrovich-matc#11]
Please let me know if you will keep a 0 out of 8 on this assignment, or if you plan to submit it this week.

**Comment by vanufrovich-matc** [comment]
I am sorry, I forgot to create an issue for week4, but I completed it on September 25th. Please, whenever you get a chance, take a look at it. Week 4 sequences.py is ready for grading.
Thank you!

**Comment by cethenmc** [comment]
Hi, Viktoryia.  Are you certain what you pushed to Git Hub for week 4 was your final copy?  I receive the following when I run it.

![image](https://user-images.githubusercontent.com/112707666/199603112-f7abc676-7e01-4d32-941f-a39e29ad6cdf.png)

**Comment by vanufrovich-matc** [comment]
Hi Chris,
Yes, I did, and I see it in my files, but I will recreate this from scratch to make sure you can run it: maybe I missed some commands there. I am so sorry for confusion here.
Thank you!

**Comment by cethenmc** [comment]
No problem at all.  Since you see it in your files let me check git hub web one more time.



Chris

[signature_146958654]
Chris Ethen | Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by cethenmc** [comment]
You definitely submitted it on 9/25.  Let me see if I can figure out why it does not pull down.  Please do not redo.  I don't want to make you do extra work!

![image](https://user-images.githubusercontent.com/112707666/199970548-ed05681c-f8a6-41e8-bc70-fedfab352132.png)

**Comment by cethenmc** [comment]
I am to the bottom of it, Viktoryia!  So you never created an Issue ticket for Week 4, and I did see the code out there, but the code doesn't run.

![image](https://user-images.githubusercontent.com/112707666/199971955-d7c3250d-4692-42c4-b33a-6f081c334ceb.png)

As a result, I thought you were not done, and that you'd submit an Issue ticket when it was ready to grade.  If you could please repair it, then you could reply to this ticket when ready for it to be regraded.

Thanks.

Chris

**Comment by vanufrovich-matc** [comment]
Week 4 lab is ready for grading.
Thank you!

**Comment by cethenmc** [comment]
This is perfect!  Well done!
