### ISSUE TITLE
Week13 lab is ready for grading

### ISSUE THREAD

**Issue by vanufrovich-matc** [madisoncollege-it-programs/python-scripting-vanufrovich-matc#15]

**Comment by cethenmc** [comment]
Really nice job again.

A couple of things to help you.

- The requirements asked you to print the title before the links.  It would be best if you had placed that print line above the 'for loop'.
- You print the HTML tags with the title.  You were asked to not print the tags.  Please change your code from print(soup.title) to print(soup.title.text).
- We should change the question to print both the link label and the link.  Feel free to modify your print statement in your loop if you desire:  print(f"{link.text}:  {link.get('href')}")

I have to take a half point off for the title having tags.  7.5 out of 8.  Please reply to this ticket to let me know if you prefer keeping the 7.5 or when you've pushed your corrections to GitHub.

**Comment by vanufrovich-matc** [comment]
I prefer keeping the 7.5
Thank you!

**Comment by cethenmc** [comment]
Thank you for getting back to me.  I will close this GitHub Issue ticket.
