### ISSUE TITLE
Ready for grading week 2 my first script assignment 

### ISSUE THREAD

**Issue by vanufrovich-matc** [madisoncollege-it-programs/python-scripting-vanufrovich-matc#2]

**Comment by cethenmc** [comment]
Hi, Viktoryia.  I would like you to update your script so you can run it from the command line.

Your first line should always be the following for your scripts. In this way, if you are running from the command line it will know what interpreter to use. Will you please add this line to the top of your first-script.py code?

#!/usr/bin/env python3

Recall from the videos, you may also need to issue a chmod command to modify the rights to make it executable.

chmod u+x first-script.py

After this, you can execute from the command line.

./first-script.py

Please be so kind as to resubmit it, so...
    1. modify the file in NetLab with the added line at the top.
    2. update the file to be executable.
    3. add the file to staging (git add .)
    4. commit the file to your local repo. (git commit -m "changes requested to run from command line")
    5. push to the git hub repository (git push)
    6. reply to this same issue, saying you have completed these steps

Thanks.

~Chris

**Comment by vanufrovich-matc** [comment]
Hello Chris,

I am sorry I have just noticed this comment after you sent me an email, sure I will fix all the above.

Thank you!

**Comment by cethenmc** [comment]
Thank you, Viktoryia.  I hope you had a nice weekend.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by cethenmc** [comment]
Wow.  Super nicely done!  I will mention that I would like to see more explicitly named variables (instead of 'x'), and if logic after the colon carriage returned and indented.  We do try to teach this as standard in the slides and videos.  Still, beautiful work!  33/33

**Comment by cethenmc** [comment]
This file is not executable at the command line level.  As a result, I recorded 6 out of 8.  You are welcome to correct that and reply to this issue ticket when you have pushed to GitHub for me to re-grade.

**Comment by vanufrovich-matc** [comment]
Hi Chris,

I have just made the file executable and pushed to GitHub. It is ready for your review whenever you have a moment. Thanks for pointing that out to me, appreciate it.

Thank you!

**Comment by cethenmc** [comment]
Thank you!  Changed to full credit in the grade book!
