### ISSUE TITLE
Ready for grading assignment week6 flow control

### ISSUE THREAD

**Issue by vanufrovich-matc** [madisoncollege-it-programs/python-scripting-vanufrovich-matc#5]

**Comment by cethenmc** [comment]
Full credit earned.  You satisfied the third door requirement!  And that beach in Mexico sounds great!  

Under Spain, if they chose something completely different, it would have been nice to see some output telling them the user did not choose one of the options.  So basically an else like you did for door 3.

Also switching whatever their input is to make it evaluated to lower() (lowercase) would help give nice functionality if the spelled the right answer in the wrong case.

Still nicely done, and I love the different country idea.

Thanks!
