### ISSUE TITLE
Ready for Grading midterm-if.py Project #1 - Flow Control

### ISSUE THREAD

**Issue by vanufrovich-matc** [madisoncollege-it-programs/python-scripting-vanufrovich-matc#7]

**Comment by cethenmc** [comment]
Wow.  Super nicely done!  I will mention that I would like to see more explicitly named variables (instead of 'x'), and if logic after the colon carriage returned and indented.  We do try to teach this as standard in the slides and videos.  Still, beautiful work!  33/33
