### ISSUE TITLE
Ready for Grading midterm-jpark.py Project #2 - Jurassic Park

### ISSUE THREAD

**Issue by vanufrovich-matc** [madisoncollege-it-programs/python-scripting-vanufrovich-matc#8]

**Comment by cethenmc** [comment]
Nice work overall.  Upon successful login, the "done" option is missing [enter command ("reboot","shutdown",""):].  Additionally, those instructions were to be pulled from the command_database and not hard-coded.  (2 pts)  If I carriage return (meaning providing a null), it just finishes the program with no more printouts.  That occurs for any letter I type in.  However, when I type in "done," it prints the clause expected.  A bigger issue is when you log in on your third attempt, and you execute any command.  The user gets the correct response followed by 25 magic word clauses (2 pt).  29/33
